spring:
  application:
    name: rest-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_db?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 123123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
